services:
  db:
    image: beercan1989/arm-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: v7i8t1o2r9
    ports:
      - "3306:3306"
    expose:
      - "3306"
    container_name: mysql
    volumes:
      - /var/lib/mysql
  postgres:
    image: arm32v5/postgres
    volumes:
      - /var/lib/postgresql
    environment:
      POSTGRES_DB: timesheet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: v7i8t1o2r9
    ports:
      - 5432:5432
  aplicacao:
    image: pontoceub-backend
    restart: always
    ports:
      - "8084:8080"
    container_name: pontoceub-backend

