services:
  postgres:
    container_name: pontoceub-db-postgres
    image: arm32v5/postgres
    restart: always
    volumes:
      - /var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: v7i8t1o2r9
    ports:
      - "5432:5432"
    expose:
      - "5432"
  aplicacao:
    container_name: pontoceub-backend
    image: pontoceub-backend
    restart: always
    ports:
      - "8084:8080"


